### ISSUE TITLE
cannot init the dataset, data.zip is gone?

### ISSUE THREAD

**Issue by suredream** [TUM-LMF/BreizhCrops#4]
Python 3.8.2 | packaged by conda-forge | (default, Feb 27 2020, 19:33:47) 
[Clang 9.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.

```
>>> from breizhcrops import BreizhCrops
>>> BreizhCrops(root="data",region="frh01")


Initializing BreizhCrops region frh01
classmapping.csv: 0.00B [00:01, ?B/s]
Traceback (most recent call last):
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jun.xiong/Desktop/projects/breizhcrops/breizhcrops/datasets/breizhcrops.py", line 57, in __init__
    self.load_classmapping(classmapping)
  File "/Users/jun.xiong/Desktop/projects/breizhcrops/breizhcrops/datasets/breizhcrops.py", line 128, in load_classmapping
    download_file(CLASSMAPPINGURL, classmapping)
  File "/Users/jun.xiong/Desktop/projects/breizhcrops/breizhcrops/utils.py", line 43, in download_file
    urllib.request.urlretrieve(url, filename=output_path, reporthook=t.update_to)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/jun.xiong/anaconda/envs/breizhcrops/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)>
```

**Comment by suredream** [comment]
```
(breizhcrops) ➜  data git:(master) bash download.sh 
--2020-02-27 15:44:11--  https://storage.googleapis.com/breizhcrops/data.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 108.177.122.128
Connecting to storage.googleapis.com (storage.googleapis.com)|108.177.122.128|:443... connected.
ERROR: cannot verify storage.googleapis.com's certificate, issued by ‘emailAddress=certadmin@netskope.com,CN=ca.climate.goskope.com,OU=3befc29fdf0e1b617715af2eaac6bf8e,O=Monsanto,L=St. Louis,ST=MO,C=US’:
  Self-signed certificate encountered.
To connect to storage.googleapis.com insecurely, use `--no-check-certificate'.
unzip:  cannot find or open data.zip, data.zip.zip or data.zip.ZIP.
rm: data.zip: No such file or directory
```

**Comment by MarcCoru** [comment]
Hey,
Thanks for the issue. I didn't encounter this before. I just tested the download and it seems to work for me.

From the error-log, it seems to be connected with a "self signed certificate" in both cases (from both independent Google Cloud Storage and LRZ servers). Do you have some special certificates on your machine?

Could you try 
`wget --no-check-certificate https://storage.googleapis.com/breizhcrops/data.zip`
with and without the certificate flag `--no-check-certificate`?

There are individual dataset download URLs in `https://github.com/TUM-LMF/BreizhCrops/blob/master/breizhcrops/datasets/breizhcrops.py`

Datasets:
```
FRH01URL = "https://syncandshare.lrz.de/dl/fiA33ywfHQdzbxXwYQ5zLVpp/frh01.zip"
FRH02URL = "https://syncandshare.lrz.de/dl/fi2pg7sXMjTQRSzrWxRdGLux/frh02.zip"
FRH03URL = "https://syncandshare.lrz.de/dl/fiFbj4sqWYzd4kmcEThTJzYC/frh03.zip"
FRH04URL = "https://syncandshare.lrz.de/dl/fi6rE9rgVyPqS5T5yN6Fccv5/frh04.zip"
```

Shapefiles
```
FRH01_SHP_URL = "https://syncandshare.lrz.de/dl/fiAHe7ZYMerBi2yJ5hKJmTXS/frh01.tar.gz"
FRH02_SHP_URL = "https://syncandshare.lrz.de/dl/fi8L5iwpJXs2b9hKEFjQoML5/frh02.tar.gz"
FRH03_SHP_URL = "https://syncandshare.lrz.de/dl/fiTdWAa8b9K4XVmrBbZ6413i/frh03.tar.gz"
FRH04_SHP_URL = "https://syncandshare.lrz.de/dl/fiKfoL1VW9jiDXPgnVXu7ZFK/frh04.tar.gz"
```
Maybe downloading them through Browser (or `wget`) would help.
Let me know if it does or does not work

Marc

**Comment by suredream** [comment]
Hi Marc:

```wget --no-check-certificate https://storage.googleapis.com/breizhcrops/data.zip
```
Works, thanks,
